export const products = [{
        id: 1,
        title: "Super Smash Bros. Ultimate",
        price: 59.90,
        category: "nintendo switch",
        image: "https://img.icons8.com/color/96/000000/super-smash-bros.png",
        rating: {
            rate: 4.5,
            count: 120,
        },
    },
    {
        id: 2,
        title: "The Legend of Zelda: Breath of the Wild",
        price: 50.90,
        category: "men's clothing",
        image: "https://img.icons8.com/color/96/000000/triforce.png",
        rating: {
            rate: 4.1,
            count: 259,
        },
    },
    {
        id: 3,
        title: "Super Mario Odyssey",
        price: 50.90,
        category: "nintendo switch",
        image: "https://img.icons8.com/color/96/000000/super-mario.png",
        rating: {
            rate: 4.7,
            count: 500,
        },
    },
    {
        id: 4,
        title: "The Sims Collection",
        price: 15.99,
        category: "nintendo switch",
        image: "https://img.icons8.com/color/144/000000/the-sims--v2.png",
        rating: {
            rate: 2.1,
            count: 430,
        },
    },
    {
        id: 5,
        title: "Cuphead",
        price: 19.92,
        category: "nintendo switch",
        image: "https://img.icons8.com/color/96/000000/mugman.png",
        rating: {
            rate: 4.6,
            count: 400,
        },
    },
    {
        id: 6,
        title: "Terraria",
        price: 10.00,
        category: "Digital",
        image: "https://img.icons8.com/color/48/000000/best-terraria.png",
        rating: {
            rate: 3.9,
            count: 70,
        },
    },
    {
        id: 7,
        title: "Fortnite V-Bucks",
        price: 9.99,
        category: "Digital",
        image: "https://img.icons8.com/color/96/000000/fortnite-battle-royale.png",
        rating: {
            rate: 3,
            count: 400,
        },
    },
    {
        id: 8,
        title: "Sonic at the Olympic Games Tokyo 2020",
        price: 10.99,
        category: "nintendo switch",
        image: "https://img.icons8.com/color/96/000000/sonic-the-hedgehog-1.png",
        rating: {
            rate: 1.9,
            count: 100,
        },
    },
    {
        id: 9,
        title: "Day of the Tentacle",
        price: 15.00,
        category: "Digital",
        image: "https://img.icons8.com/color/48/000000/day-of-the-tentacle.png",
        rating: {
            rate: 3.3,
            count: 203,
        },
    },
    {
        id: 10,
        title: "Luigi's Mansion 3",
        price: 50.99,
        category: "nintendo switch",
        image: "https://img.icons8.com/color/96/000000/luigi.png",
        rating: {
            rate: 2.9,
            count: 470,
        },
    },
    {
        id: 11,
        title: "Among Us",
        price: 15.00,
        category: "Digital",
        image: "https://img.icons8.com/color/96/000000/among-us.png",
        rating: {
            rate: 4.8,
            count: 319,
        },
    },
    {
        id: 12,
        title: "NARUTO SHIPPUDEN: Ultimate Ninja STORM 4",
        price: 45.00,
        category: "PS4",
        image: "https://img.icons8.com/color/96/000000/naruto.png",
        rating: {
            rate: 4.8,
            count: 400,
        },
    },
    {
        id: 13,
        title: "60 Seconds",
        price: 15.00,
        category: "Digital",
        image: "https://img.icons8.com/color/96/000000/60-seconds.png",
        rating: {
            rate: 2.9,
            count: 250,
        },
    },
    {
        id: 14,
        title: "Crash Bandicoot 4: It’s About Time PlayStation 4 ",
        price: 45.00,
        category: "PS5",
        image: "https://img.icons8.com/color/96/000000/crash-bandicoot.png",
        rating: {
            rate: 2.2,
            count: 140,
        },
    },
    {
        id: 15,
        title: "Overwatch",
        price: 25.99,
        category: "Digital",
        image: "https://img.icons8.com/color/96/000000/overwatch--v1.png",
        rating: {
            rate: 2.6,
            count: 235,
        },
    },
    {
        id: 16,
        title: "Nintendo Switch Oled",
        price: 250.00,
        category: "nintendo switch",
        image: "https://img.icons8.com/color/96/000000/nintendo-switch.png",
        rating: {
            rate: 2.9,
            count: 340,
        },
    },
    {
        id: 17,
        title: "Minecraft",
        price: 15.00,
        category: "Digital",
        image: "https://img.icons8.com/color/48/000000/minecraft-sword.png",
        rating: {
            rate: 3.8,
            count: 679,
        },
    },
    {
        id: 18,
        title: "Genshin Impact Credits",
        price: 10.00,
        category: "Digital",
        image: "https://img.icons8.com/color/96/000000/genshin-impact.png",
        rating: {
            rate: 4.7,
            count: 130,
        },
    },
    {
        id: 19,
        title: "Pokémon Diamante Lucente, Switch",
        price: 55.00,
        category: "nintendo switch",
        image: "https://img.icons8.com/color/96/000000/pokeball--v1.png",
        rating: {
            rate: 4.5,
            count: 146,
        },
    },
    {
        id: 20,
        title: "Animal Crossing: New Horizons",
        price: 55.00,
        category: "nintendo switch",
        image: "https://img.icons8.com/color/96/000000/animal-crossing.png",
        rating: {
            rate: 4.6,
            count: 145,
        },
    },
];